name: Quality Monitor
description: Action that monitors the quality of projects and pull requests.

inputs:
  config:
    description: "Quality monitor configuration (if not set the default configuration will be used)"
    required: false
  checks-name:
    description: "Name of the GitHub checks (if not set the default name will be used)"
    required: false
  pr-number:
    description: "Pull request number (if not set, PR comments will be skipped)"
    required: false
  github-token:
    description: "GitHub authentication token (GITHUB_TOKEN)"
    required: false
    default: ${{github.token}}
  github-api-url:
    description: "GitHub API URL (GITHUB_API_URL)"
    required: false
    default: ${{github.api_url}}
  skip-annotations:
    description: "Skip the creation of annotations (for warnings and missed coverage) if not empty"
    required: false
  show-headers:
    description: "Show headers for each subsection in the summary (if not set, headers are hidden)"
    required: false
  max-warning-annotations:
    description: "Limit the number of warning annotations at specific lines. By default, all annotations are created."
    required: false
  max-coverage-annotations:
    description: "Limit the number of coverage annotations at specific lines. By default, all annotations are created."
    required: false
  title-metric:
    description: "Which metric to show in the GitHub check title (options: line, branch, instruction, mutation, style-issues, none)"
    required: false
  quality-gates:
    description: "Quality gates configuration as JSON following Jenkins coverage plugin format (optional)"
    required: false
  sha:
    description: "Commit SHA to use for the quality check (if not set, GITHUB_SHA will be used)"
    required: false

runs:
  using: 'docker'
  image: 'docker://uhafner/quality-monitor:3.1.0-SNAPSHOT'
  env:
    CONFIG: ${{ inputs.config }}
    CHECKS_NAME: ${{ inputs.checks-name }}
    PR_NUMBER: ${{ inputs.pr-number }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GITHUB_API_URL: ${{ inputs.github-api-url }}
    SKIP_ANNOTATIONS: ${{ inputs.skip-annotations }}
    SHOW_HEADERS: ${{ inputs.show-headers }}
    MAX_WARNING_ANNOTATIONS: ${{ inputs.max-warning-annotations }}
    MAX_COVERAGE_ANNOTATIONS: ${{ inputs.max-coverage-annotations }}
    TITLE_METRIC: ${{ inputs.title-metric }}
    QUALITY_GATES: ${{ inputs.quality-gates }}
    SHA: ${{ inputs.sha }}

branding:
  icon: check-square
  color: green
