name: Eat your own dog food

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed

jobs:
  eat-your-own-dogfood:
    name: Run Snapshot version of quality monitor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Cache the NVD database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check
      - name: Build with Maven
        env:
          BROWSER: chrome-container
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -V --color always -ntp clean verify -Ppit -Pci -Powasp | tee maven.log
          if [ "${PIPESTATUS[0]}" != "0" ]; then
            exit 1;
          fi
      - name: Read Quality Monitor Configuration
        id: quality-monitor
        run: echo "json=$(jq -c . .github/quality-monitor.json)" >> "$GITHUB_OUTPUT"
      - name: Read Quality Gates Configuration
        id: quality-gates
        run: echo "json=$(jq -c . .github/quality-gates.json)" >> "$GITHUB_OUTPUT"
      - name: Run Quality Monitor of main branch
        uses: uhafner/quality-monitor@main
        with:
          config: ${{ steps.quality-monitor.outputs.json }}
          quality-gates: ${{ steps.quality-gates.outputs.json }}
          comments-strategy: ADD
          show-headers: true
          title-metric: none
